general:
  prediction_steps: 40

train:
  n_epochs: 20000000
  batch_size: 25
  data_path: '/Users/adam/Documents/PycharmProjects/CSE598_SwarmNetApplication/SwarmNet - PyTorch/SwarmData.json'
  loss: "mse"
  optimizer: "adam"
  env_width: 1400
  env_height: 1000
  add_noise: False
  sample_size: "max"
  curriculum: True

test:
  data_path: '/Users/adam/Documents/PycharmProjects/CSE598_SwarmNetApplication/SwarmNet - PyTorch/SwarmData.json'
  env_width: 2550
  env_height: 1650
  truth_available: True
  add_noise: False

model:
  name: "SwarmNet"
  save_path: 'C:\Users\ahard_000\Documents\ASU stuff'
  save_strategy: ""
  # Train model or test existing model
  mode: "test"
  # Create new model for training or train existing model
  load_train: True
  load_path: '/Users/adam/Documents/PycharmProjects/CSE598_SwarmNetApplication/SwarmNet - PyTorch/models/model_10_step.pkl'