general:
  prediction_steps: 1

train:
  n_epochs: 20000000
  batch_size: 100
  data_path: 'C:\Users\ahard_000\Documents\ASU stuff\SwarmData.json'
  loss: "mse"
  optimizer: "adam"
  env_width: 1400
  env_height: 1000
  add_noise: False
  sample_size: "max"

test:
  data_path: 'C:\Users\ahard_000\Documents\ASU stuff\SwarmData_2.json'
  env_width: 2550
  env_height: 1650
  truth_available: True
  add_noise: False

model:
  name: "SwarmNet"
  save_path: 'C:\Users\ahard_000\Documents\ASU stuff'
  save_strategy: ""
  # Train model or test existing model
  mode: "test"
  # Create new model for training or train existing model
  load_train: False
  load_path: 'C:\Users\ahard_000\Documents\ASU stuff\model_test.pkl'